WIP: trying some stuff real quick friends

diff --git a/container/root/etc/cont-init.d/50-init-dgoss b/container/root/etc/cont-init.d/50-init-dgoss
--- a/container/root/etc/cont-init.d/50-init-dgoss
+++ b/container/root/etc/cont-init.d/50-init-dgoss
@@ -33,7 +33,75 @@ foreground { s6-echo " [run] goss jhbuild tests" }
 # /usr/local/bin/goss -g /tests/goss.jhbuild.yaml validate --retry-timeout 30s --sleep 1s
 
 # Okay I think this will actually run the tests like the pi user
-su - pi -c "/usr/local/bin/goss -g /tests/goss.jhbuild.yaml validate --retry-timeout 30s --sleep 1s"
+# su - pi -c "/usr/local/bin/goss -g /tests/goss.jhbuild.yaml validate --retry-timeout 30s --sleep 1s"
+
+with-contenv
+s6-envuidgid pi
+multisubstitute
+{
+  import -u -D0 UID
+  import -u -D0 GID
+  import -u -D0 DEBIAN_FRONTEND
+  import -u -D0 LANG
+  import -u -D0 LC_ALL
+  import -u -D0 UNAME
+  import -u -D0 NOT_ROOT_USER
+  import -u -D0 USER_HOME
+  import -u -D0 PROJECT_HOME
+  import -u -D0 LANG
+  import -u -D0 SKIP_ON_TRAVIS
+  import -u -D0 CURRENT_DIR
+  import -u -D0 GSTREAMER
+  import -u -D0 ENABLE_PYTHON3
+  import -u -D0 ENABLE_GTK
+  import -u -D0 PYTHON_VERSION_MAJOR
+  import -u -D0 PYTHON_VERSION
+  import -u -D0 PREFIX
+  import -u -D0 JHBUILD
+  import -u -D0 PATH
+  import -u -D0 LD_LIBRARY_PATH
+  import -u -D0 PYTHONPATH
+  import -u -D0 PKG_CONFIG_PATH
+  import -u -D0 XDG_DATA_DIRS
+  import -u -D0 XDG_CONFIG_DIRS
+  import -u -D0 PYTHON
+  import -u -D0 NOTVISIBLE
+  import -u -D0 VIRTUALENVWRAPPER_PYTHON
+  import -u -D0 VIRTUALENVWRAPPER_VIRTUALENV
+  import -u -D0 VIRTUALENV_WRAPPER_SH
+  import -u -D0 PYTHONUNBUFFERED
+  import -u -D0 PYTHON_VERSION_MAJOR
+  import -u -D0 GSTREAMER
+  import -u -D0 USER
+  import -u -D0 USER_HOME
+  import -u -D0 LANGUAGE_ID
+  import -u -D0 GITHUB_BRANCH
+  import -u -D0 GITHUB_REPO_NAME
+  import -u -D0 GITHUB_REPO_ORG
+  import -u -D0 PI_HOME
+  import -u -D0 MAIN_DIR
+  import -u -D0 VIRT_ROOT
+  import -u -D0 PKG_CONFIG_PATH
+  import -u -D0 SCARLETT_CONFIG
+  import -u -D0 SCARLETT_HMM
+  import -u -D0 SCARLETT_LM
+  import -u -D0 SCARLETT_DICT
+  import -u -D0 LD_LIBRARY_PATH
+  import -u -D0 GST_PLUGIN_PATH
+  import -u -D0 PYTHON
+  import -u -D0 PYTHON_VERSION
+  import -u -D0 VIRTUALENVWRAPPER_PYTHON
+  import -u -D0 VIRTUALENVWRAPPER_VIRTUALENV
+  import -u -D0 VIRTUALENVWRAPPER_SCRIPT
+  import -u -D0 PYTHONSTARTUP
+  import -u -D0 PIP_DOWNLOAD_CACHE
+  import -u -D0 WORKON_HOME
+  import -u -D0 USER_SSH_PUBKEY
+  import -u -D0 HOME
+}
+/usr/local/bin/goss -g /tests/goss.jhbuild.yaml validate --retry-timeout 30s --sleep 1s
+
+# /bin/bash -C "/usr/local/bin/goss -g /tests/goss.jhbuild.yaml validate --retry-timeout 30s --sleep 1s"
 
 ######################################################################
 # source: claw-docker-base
@@ -53,7 +121,13 @@ su - pi -c "/usr/local/bin/goss -g /tests/goss.jhbuild.yaml validate --retry-tim
 ######################################################################
 
 ## Signal build complete if running on ci ##
-if [[ $TRAVIS_CI ]]; then
-  echo " [run] finished running jhbuild goss tests ... sending signal complete"
-  exit $SIGNAL_BUILD_STOP
-fi
+# if [[ $TRAVIS_CI ]]; then
+#   echo " [run] finished running jhbuild goss tests ... sending signal complete"
+#   exit $SIGNAL_BUILD_STOP
+# fi
+
+# importas program
+# source: https://skarnet.org/software/execline/importas.html
+
+foreground { s6-echo " [ [run] finished running jhbuild goss tests ... sending signal complete" }
+exit $SIGNAL_BUILD_STOP
